# Generated by Django 2.0.13 on 2020-08-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('number', models.IntegerField(null=True)),
                ('fresh_suguni', models.IntegerField(null=True)),
                ('fresh_sugang', models.IntegerField(null=True)),
                ('fresh_limit', models.IntegerField(null=True)),
                ('sopho_suguni', models.IntegerField(null=True)),
                ('sopho_sugang', models.IntegerField(null=True)),
                ('sopho_limit', models.IntegerField(null=True)),
                ('junior_suguni', models.IntegerField(null=True)),
                ('junior_sugang', models.IntegerField(null=True)),
                ('junior_limit', models.IntegerField(null=True)),
                ('senior_suguni', models.IntegerField(null=True)),
                ('senior_sugang', models.IntegerField(null=True)),
                ('senior_limit', models.IntegerField(null=True)),
            ],
        ),
    ]
